### ISSUE TITLE
How to mock api response in laravel testing?

### ISSUE THREAD

**Issue by mg98** [spatie/geocoder#69]
Hello, after successfully setting up geocoder in my laravel project I want to write the tests. To not fire a costy api request everytime, I would like to mock responses, so called _fixtures_, for the endpoints.

I know that spatie/geocoder uses GuzzleHttp under the hood. So I looked up how to do mocking with GuzzleHttp and found snippets like
```
$this->mockHandler = new MockHandler();
$httpClient = new Client([
      'handler' => $this->mockHandler,
]);
```

That means I need to pass a MockHandler to the client instance? But the Client is instantiated in `Spatie\Geocoder\GeocoderServiceProvider`... should I publish the file and edit it by myself?

I'm just asking if there is any recommended way for this trivial task :) After all, I have never done HTTP mocking in a Laravel project!

Thanks and have a great day.

**Comment by freekmurze** [comment]
This question is out of scope for this issue tracker. 

This tweet might be usefull for you: https://twitter.com/gonedark/status/1209151834193059841

**Comment by jasonmccreary** [comment]
Thanks for the loop in. While this does use Guzzle underneath and the container, the Guzzle client is instantiated with `new`. As such, I don't believe you would have the _hooks_ to inject a mock with Guzzle's `MockHandler`.

The service provider could be updated to _resolve_ an instance of `\Guzzle\Client` from the container instead of [using `new`](https://github.com/spatie/geocoder/blob/master/src/GeocoderServiceProvider.php#L22).

However, IMO, this borders testing the `Geocoder` behavior directly which is pretty _low level_. Instead I would mock the entire `Geocoder` and to verify its methods were called as expected. This does couple the tests with the implementation, but I feel that's an acceptable tradeoff consider you've already coupled your application to the package.

**Comment by freekmurze** [comment]
> The service provider could be updated to resolve an instance of \Guzzle\Client from the container instead of using new.

Good suggestion, done!

Thanks for chiming in!
